#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 16 19:35:37 2021

@author: ceci
"""

from owlready2 import *
import owlready2 as owl
import datetime as dt

onto = get_ontology("personaRDF.owl").load()
print(onto.base_iri)

print(onto.Persona.instances())


name='persona7'
sexo='Femenino'
#creacion de la instancia
nper=onto.Persona(name)
#datatype property
nper.tieneSexo=[''+sexo]
nper.tieneFechaNacimiento=[dt.date(2021,2,17)]
print(nper.iri)
#onto.save(file = "personaRDF.owl", format = "rdfxml")
